# ===========================
# DEFAULTS (aplican a todos)
# ===========================
server:
  port: 8080

spring:
  application:
    name: blackjackapi

  # R2DBC (MySQL) - pool recomendado
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/blackjackdb
    username: root
    password: root

  # Flyway (JDBC) para migraciones
  flyway:
    url: jdbc:mysql://localhost:3306/blackjackdb
    user: root
    password: root
    enabled: true
    locations: classpath:db/migration

  # MongoDB Reactivo
  data:
    mongodb:
      uri: mongodb://localhost:27017/blackjackdb

# Logging útil en desarrollo
logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springdoc: DEBUG   # logs de springdoc para diagnosticar /v3/api-docs

# springdoc (Swagger/OpenAPI)
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs         # JSON de OpenAPI
  swagger-ui:
    enabled: true
    path: /swagger-ui.html     # UI accesible en /swagger-ui.html
    url: /v3/api-docs          # << fuerza a la UI a usar /v3/api-docs
    config-url: /v3/api-docs/swagger-config
  # (sin paths-to-match para no limitar endpoints)

# ===================================
# Perfil LOCAL: servicios en localhost
# Ejecuta: ./mvnw spring-boot:run -Dspring-boot.run.profiles=local
# ===================================
---
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/blackjackdb
    username: root
    password: root
  flyway:
    url: jdbc:mysql://localhost:3306/blackjackdb
    user: root
    password: root
    enabled: true
    locations: classpath:db/migration
  data:
    mongodb:
      uri: mongodb://localhost:27017/blackjackdb

# ===================================
# Perfil DOCKER: hostnames de docker-compose
# ===================================
---
spring:
  config:
    activate:
      on-profile: docker
  r2dbc:
    url: r2dbc:pool:mysql://mysql:3306/blackjackdb
    username: root
    password: root
  flyway:
    url: jdbc:mysql://mysql:3306/blackjackdb
    user: root
    password: root
    enabled: true
    locations: classpath:db/migration
  data:
    mongodb:
      uri: mongodb://mongo:27017/blackjackdb

# ===================================
# Perfil PROD: credenciales por variables de entorno
# ===================================
---
spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: ${R2DBC_URL:r2dbc:pool:mysql://localhost:3306/blackjackdb}
    username: ${R2DBC_USERNAME:root}
    password: ${R2DBC_PASSWORD:root}
  flyway:
    url: ${JDBC_URL:jdbc:mysql://localhost:3306/blackjackdb}
    user: ${JDBC_USERNAME:root}
    password: ${JDBC_PASSWORD:root}
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/blackjackdb}
